title: Relentless Leader
permalink: /:title.html
theme: minima

google_analytics: G-CJMG9DTHXR

description: >-
  Relentless Leader's Blog

url: "https://relentless-leader.com/"

header_pages:
  - all-posts.html
  - distributed-systems.html

license: "CC BY-NC-ND 4.0"
license_url: "creativecommons.org/licenses/by-nc-nd/4.0/"

linkedin_username: relentless-leader
github_username: relentless-leader
twitter_username: RishabhBhatia_
email: bhatiarishabh63@gmail.com

show_excerpts: true